// ui/src/App.vue
<template>
	<body>
		<audio id="audio_on" src="mic_click_on.ogg"></audio>
		<audio id="audio_off" src="mic_click_off.ogg"></audio>
		<div v-if="voice.uiEnabled" class="voiceInfo">
			<p v-if="voice.callInfo !== 0" :class="{ talking: voice.talking && !voice.usingRadio }">
				[Call]
			</p>
			<p v-if="voice.radioEnabled && voice.radioChannel !== 0" 
			   :class="{ 
			     talking: voice.usingRadio && voice.currentActiveRadio === 'primary', 
			     active: voice.currentActiveRadio === 'primary' && !voice.usingRadio
			   }">
				{{ voice.radioChannel }} MHz [Primary Radio]
			</p>
			<p v-if="voice.radioEnabled && voice.secondaryRadioChannel !== 0" 
			   :class="{ 
			     talking: voice.usingRadio && voice.currentActiveRadio === 'secondary', 
			     active: voice.currentActiveRadio === 'secondary' && !voice.usingRadio
			   }">
				{{ voice.secondaryRadioChannel }} MHz [Secondary Radio]
			</p>
			<p v-if="voice.voiceModes.length" :class="{ talking: voice.talking && !voice.usingRadio }">
				{{ voice.voiceModes[voice.voiceMode][1] }} [Range]
			</p>
		</div>
	</body>
</template>

<script setup lang="ts">
import { reactive, onMounted } from "vue";

interface VoiceState {
	uiEnabled: boolean;
	voiceModes: [number, string][];
	voiceMode: number;
	radioChannel: number;
	secondaryRadioChannel: number;
	radioEnabled: boolean;
	usingRadio: boolean;
	currentActiveRadio: string;
	callInfo: number;
	talking: boolean;
}

const voice = reactive<VoiceState>({
	uiEnabled: true,
	voiceModes: [],
	voiceMode: 0,
	radioChannel: 0,
	secondaryRadioChannel: 0,
	radioEnabled: true,
	usingRadio: false,
	currentActiveRadio: "primary",
	callInfo: 0,
	talking: false,
});

function handleMessage(event: MessageEvent) {
	const data = event.data;

	if (data.uiEnabled !== undefined) {
		voice.uiEnabled = data.uiEnabled;
	}

	if (data.voiceModes !== undefined) {
		voice.voiceModes = JSON.parse(data.voiceModes);
		// Push our own custom type for modes that have their range changed
		let voiceModes = [...voice.voiceModes];
		voiceModes.push([0.0, "Custom"]);
		voice.voiceModes = voiceModes;
	}

	if (data.voiceMode !== undefined) {
		voice.voiceMode = data.voiceMode;
	}

	if (data.radioChannel !== undefined) {
		voice.radioChannel = data.radioChannel;
	}

	if (data.secondaryRadioChannel !== undefined) {
		voice.secondaryRadioChannel = data.secondaryRadioChannel;
	}

	if (data.currentActiveRadio !== undefined) {
		voice.currentActiveRadio = data.currentActiveRadio;
	}

	if (data.radioEnabled !== undefined) {
		voice.radioEnabled = data.radioEnabled;
	}

	if (data.callInfo !== undefined) {
		voice.callInfo = data.callInfo;
	}

	if (data.usingRadio !== undefined) {
		voice.usingRadio = data.usingRadio;
	}
	
	if (data.talking !== undefined) {
		voice.talking = data.talking;
	}

	if (data.sound && voice.radioEnabled && (voice.radioChannel !== 0 || voice.secondaryRadioChannel !== 0)) {
		let click = document.getElementById(data.sound) as HTMLAudioElement;
		if (click) {
			// discard these errors as its usually just a 'uncaught promise' from two clicks happening too fast.
			click.load();
			click.volume = data.volume;
			click.play().catch(() => {});
		}
	}
}

onMounted(() => {
	window.addEventListener("message", handleMessage);
	
	fetch(`https://${(window as any).GetParentResourceName()}/uiReady`, { method: 'POST' });
});
</script>

// voice-ui/src/components/App.tsx
import React, { useEffect, useState } from 'react';
import { debugData } from '../utils/debugData';
import { fetchNui } from '../utils/fetchNui';
import { useNuiEvent } from '../hooks/useNuiEvent';
import List from './List';

debugData([
    {
        action: "Debug",
        data: true,
    },
]);

interface Voice {
    voiceModes: Array<[number, string]>;
    voiceMode: number;
    radioChannel: number;
    radioEnabled: boolean;
    usingRadio: boolean;
    callInfo: number;
    talking: boolean;
}

let EnableUI = ""

const App: React.FC = () => {
    const [debug, setDebug] = useState(false);
    const [RadioList, setRadioList] = useState<{ id: string, Name: string, Talking: boolean }[]>([]);
    const [voice, setVoice] = useState<Voice>({
        voiceModes: [],
        voiceMode: 0,
        radioChannel: 0,
        radioEnabled: true,
        usingRadio: false,
        callInfo: 0,
        talking: false,
    });

    useNuiEvent("Debug", (data: string) => {
        setDebug(true);
        EnableUI = 'true'
        setVoice((prevVoice) => ({
            ...prevVoice,
            radioChannel: 1,
            radioEnabled: true,
        }));
    });

    useEffect(() => {
        const handleMessage = (event: MessageEvent) => {
            const data = event.data;
            setVoice((prevVoice) => ({
                ...prevVoice,
                voiceModes: data.voiceModes !== undefined ? [...JSON.parse(data.voiceModes), [0.0, "Custom"]] : prevVoice.voiceModes,
                voiceMode: data.voiceMode !== undefined ? data.voiceMode : prevVoice.voiceMode,
                radioChannel: data.radioChannel !== undefined ? data.radioChannel : prevVoice.radioChannel,
                radioEnabled: data.radioEnabled !== undefined ? data.radioEnabled : prevVoice.radioEnabled,
                callInfo: data.callInfo !== undefined ? data.callInfo : prevVoice.callInfo,
                usingRadio: data.usingRadio !== undefined ? data.usingRadio : prevVoice.usingRadio,
                talking: data.talking !== undefined ? data.talking : prevVoice.talking,
            }));
            if (data.sound) {
                const click = document.getElementById(data.sound) as HTMLAudioElement;
                if (click) {
                    click.load();
                    if (data.volume !== undefined) {
                        click.volume = data.volume;
                    }
                    click.play()
                }
            }
            if (EnableUI === "") {
                EnableUI = data.uiEnabled
            }
            if (data.RadioList !== undefined) {
                if (Array.isArray(data.RadioList)) {
                    setRadioList(data.RadioList);
                }
            }
        };

        window.addEventListener("message", handleMessage);
        fetchNui("uiReady", {});

        return () => {
            window.removeEventListener("message", handleMessage);
        };
    }, [voice.radioEnabled, voice.radioChannel]);

    return (
        <div>
            <div style={{ visibility: (EnableUI == "true" || EnableUI == "radio") ? "visible" : "hidden" }}>
                {voice.radioEnabled && voice.radioChannel !== 0 && (
                    <List radioList={RadioList} />
                )}
            </div>
            <div style={{ visibility: EnableUI == "true" ? "visible" : "hidden" }} className="fixed bottom-[5px] right-[5px] text-right text-gray-pma text-[0.75rem] font-bold text-shadow-black">
                {debug && <p>Noraml [RANGE]</p>}
                {voice.callInfo !== 0 && (
                    <p className={`${voice.talking ? "text-gray-talking" : ""} transition-colors duration-300`}>
                        [Call]
                    </p>
                )}
                {voice.radioEnabled && voice.radioChannel !== 0 && (
                    <p className={`${voice.usingRadio ? "text-gray-talking" : ""} transition-colors duration-300`}>
                        {voice.radioChannel} Mhz [Radio]
                    </p>
                )}
                {voice.voiceModes.length > 0 && (
                    <p className={`${!voice.usingRadio && voice.talking ? "text-gray-talking" : ""} transition-colors duration-300`}>
                        {voice.voiceModes[voice.voiceMode][1]} [Range]
                    </p>
                )}
            </div>
            <audio id="audio_on" src="sounds/mic_click_on.ogg" preload="auto" />
            <audio id="audio_off" src="sounds/mic_click_off.ogg" preload="auto" />
        </div>
    );
};

export default App;
