// voice-ui/src/components/App.tsx
import React, { useEffect, useState } from 'react';
import { debugData } from '../utils/debugData';
import { fetchNui } from '../utils/fetchNui';
import { useNuiEvent } from '../hooks/useNuiEvent';
import List from './List';

debugData([
    {
        action: "Debug",
        data: true,
    },
]);

interface Voice {
    voiceModes: Array<[number, string]>;
    voiceMode: number;
    radioChannel: number;
    radioEnabled: boolean;
    usingRadio: boolean;
    callInfo: number;
    talking: boolean;
}

let EnableUI = ""

const App: React.FC = () => {
    const [debug, setDebug] = useState(false);
    const [RadioList, setRadioList] = useState<{ id: string, Name: string, Talking: boolean }[]>([]);
    const [voice, setVoice] = useState<Voice>({
        voiceModes: [],
        voiceMode: 0,
        radioChannel: 0,
        radioEnabled: true,
        usingRadio: false,
        callInfo: 0,
        talking: false,
    });

    useNuiEvent("Debug", (data: string) => {
        setDebug(true);
        EnableUI = 'true'
        setVoice((prevVoice) => ({
            ...prevVoice,
            radioChannel: 1,
            radioEnabled: true,
        }));
    });

    useEffect(() => {
        const handleMessage = (event: MessageEvent) => {
            const data = event.data;
            setVoice((prevVoice) => ({
                ...prevVoice,
                voiceModes: data.voiceModes !== undefined ? [...JSON.parse(data.voiceModes), [0.0, "Custom"]] : prevVoice.voiceModes,
                voiceMode: data.voiceMode !== undefined ? data.voiceMode : prevVoice.voiceMode,
                radioChannel: data.radioChannel !== undefined ? data.radioChannel : prevVoice.radioChannel,
                radioEnabled: data.radioEnabled !== undefined ? data.radioEnabled : prevVoice.radioEnabled,
                callInfo: data.callInfo !== undefined ? data.callInfo : prevVoice.callInfo,
                usingRadio: data.usingRadio !== undefined ? data.usingRadio : prevVoice.usingRadio,
                talking: data.talking !== undefined ? data.talking : prevVoice.talking,
            }));
            if (data.sound) {
                const click = document.getElementById(data.sound) as HTMLAudioElement;
                if (click) {
                    click.load();
                    if (data.volume !== undefined) {
                        click.volume = data.volume;
                    }
                    click.play()
                }
            }
            if (EnableUI === "") {
                EnableUI = data.uiEnabled
            }
            if (data.RadioList !== undefined) {
                if (Array.isArray(data.RadioList)) {
                    setRadioList(data.RadioList);
                }
            }
        };

        window.addEventListener("message", handleMessage);
        fetchNui("uiReady", {});

        return () => {
            window.removeEventListener("message", handleMessage);
        };
    }, [voice.radioEnabled, voice.radioChannel]);

    return (
        <div>
            <div style={{ visibility: (EnableUI == "true" || EnableUI == "radio") ? "visible" : "hidden" }}>
                {voice.radioEnabled && voice.radioChannel !== 0 && (
                    <List radioList={RadioList} />
                )}
            </div>
            <div style={{ visibility: EnableUI == "true" ? "visible" : "hidden" }} className="fixed bottom-[5px] right-[5px] text-right text-gray-pma text-[0.75rem] font-bold text-shadow-black">
                {debug && <p>Noraml [RANGE]</p>}
                {voice.callInfo !== 0 && (
                    <p className={`${voice.talking ? "text-gray-talking" : ""} transition-colors duration-300`}>
                        [Call]
                    </p>
                )}
                {voice.radioEnabled && voice.radioChannel !== 0 && (
                    <p className={`${voice.usingRadio ? "text-gray-talking" : ""} transition-colors duration-300`}>
                        {voice.radioChannel} Mhz [Radio]
                    </p>
                )}
                {voice.voiceModes.length > 0 && (
                    <p className={`${!voice.usingRadio && voice.talking ? "text-gray-talking" : ""} transition-colors duration-300`}>
                        {voice.voiceModes[voice.voiceMode][1]} [Range]
                    </p>
                )}
            </div>
            <audio id="audio_on" src="sounds/mic_click_on.ogg" preload="auto" />
            <audio id="audio_off" src="sounds/mic_click_off.ogg" preload="auto" />
        </div>
    );
};

export default App;

// voice-ui/src/App.vue
<template>
	<body>
		<audio id="audio_on" src="mic_click_on.ogg"></audio>
		<audio id="audio_off" src="mic_click_off.ogg"></audio>
		<div class="voiceInfo">
			<p v-if="voice.callInfo !== 0" :class="{ talking: voice.talking }">
				[Call]
			</p>
			<p v-if="voice.radioEnabled && voice.radioChannel !== 0" :class="{ talking: voice.usingRadio }">
				{{ voice.radioChannel }} Mhz [Radio]
			</p>
			<p v-if="voice.voiceModes.length" :class="{ talking: voice.talking }">
				{{ voice.voiceModes[voice.voiceMode][1] }} [Range]
			</p>
		</div>
	</body>
</template>

<script>
import { reactive } from "vue";
export default {
	name: "App",
	setup() {
		const voice = reactive({
			voiceModes: [],
			voiceMode: 0,
			radioChannel: 0,
			radioEnabled: false,
			usingRadio: false,
			callInfo: 0,
			talking: false,
		});

		// stops from toggling voice at the end of talking
		window.addEventListener("message", function(event) {
			const data = event.data;

			if (data.voiceModes !== undefined) {
				voice.voiceModes = JSON.parse(data.voiceModes);
			}

			if (data.voiceMode !== undefined) {
				voice.voiceMode = data.voiceMode;
			}

			if (data.radioChannel !== undefined) {
				voice.radioChannel = data.radioChannel;
			}

			if (data.radioEnabled !== undefined) {
				voice.radioEnabled = data.radioEnabled;
			}

			if (data.callInfo !== undefined) {
				voice.callInfo = data.callInfo;
			}

			if (data.usingRadio !== undefined && data.usingRadio !== voice.usingRadio) {
				voice.usingRadio = data.usingRadio;
			}
			
			if ((data.talking !== undefined) && !voice.usingRadio) {
				voice.talking = data.talking;
			}

			if (data.sound && voice.radioEnabled) {
				let click = document.getElementById(data.sound);
				// discard these errors as its usually just a 'uncaught promise' from two clicks happening too fast.
				click.load();
				click.volume = data.volume;
				click.play().catch((e) => {});
			}
		});

		return { voice };
	},
};
</script>

<style>
.voiceInfo {
	font-family: Avenir, Helvetica, Arial, sans-serif;
	position: fixed;
	text-align: right;
	bottom: 5px;
	padding: 0;
	right: 5px;
	font-size: 12px;
	font-weight: bold;
	color: rgb(148, 150, 151);
	/* https://stackoverflow.com/questions/4772906/css-is-it-possible-to-add-a-black-outline-around-each-character-in-text */
	text-shadow: 1.25px 0 0 #000, 0 -1.25px 0 #000, 0 1.25px 0 #000,
		-1.25px 0 0 #000;
}
.talking {
	color: rgba(255, 255, 255, 0.822);
}
p {
	margin: 0;
}
</style>
